sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - DOCKER_REG=vterdunov

script:
  - make build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker tag docktor:${COMMIT} ${DOCKER_REG}/docktor:latest;
      docker push ${DOCKER_REG}/docktor:${COMMIT};
      docker push ${DOCKER_REG}/docktor:latest;
    fi
