---
version: '3'

services:
  docktor:
    build: .
    image: docktor
    volumes:
     - '/var/run/docker.sock:/var/run/docker.sock:rw'

  unhealthy:
    image: busybox
    logging:
      driver: 'none'
    stop_grace_period: 1s
    command: sleep 9999
    healthcheck:
      test: ["CMD", "exit 1"]
      interval: 2s
      timeout: 3s
